name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v2

      # Add a step to create the directory if it doesn't exist
      - name: Create directory
        run: |
          if [ ! -d "profile-summary-card-output" ]; then
            mkdir "profile-summary-card-output"
            echo "Directory 'profile-summary-card-output' created."
          else
            echo "Directory 'profile-summary-card-output' already exists."
          fi

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 8
          EXCLUDE: ""
          AUTO_PUSH: true
